[workspace]
members = ["crates/*", "bindings/*"]
default-members = ["crates/core", "crates/forge", "crates/liturgical-calendar"]
resolver = "2"

[workspace.package]
version = "0.5.0"
edition = "2024"

[workspace.dependencies]
liturgical-calendar-core = { version = "0.5.0", path = "crates/core" }
liturgical-calendar-forge = { version = "0.5.0", path = "crates/forge" }
liturgical-calendar = { version = "0.5.0", path = "crates/liturgical-calendar" }

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

[profile.wasm-release]
inherits = "release"
opt-level = "z"
lto = true
codegen-units = 1
strip = true
